service: dorametrix

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region:  ${opt:region, 'us-east-1'}
  memorySize: ${opt:memory, 512}
  timeout: 10
  logRetentionInDays: 7
  versionFunctions: false
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  stackTags:
    Usage: ${self:service}
  tags:
    Usage: ${self:service}
  apiGateway:
    minimumCompressionSize: 1024

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-iam-roles-per-function

package:
  individually: true

custom:
  config:
    authToken: 062df296-b152-11ed-afa1-0242ac120002
      #something # EDIT THIS TO YOUR VALUE - see for example https://www.uuidgenerator.net for getting a UUID v4
    accountNumber: 535706019673
    maxDateRange: 30
    tableName: dorametrix
    shortcutToken: 64060923-33b7-457f-91ea-4db7893273fa
    shortcutIncidentLabelId: 2805
  aws:
    databaseArn: arn:aws:dynamodb:${self:provider.region}:${self:custom.config.accountNumber}:table/${self:custom.config.tableName}
    apiGatewayCachingTtl:
      prod: 30
      dev: 0
      test: 0
    apiGatewayCachingTtlValue: ${self:custom.aws.apiGatewayCachingTtl.${self:provider.stage}, self:custom.aws.apiGatewayCachingTtl.test} # See: https://forum.serverless.com/t/api-gateway-custom-authorizer-caching-problems/4695
  esbuild:
    bundle: true
    minify: true

functions:
  AuthorizerAdd:
    handler: src/infrastructure/adapters/web/Authorizer.handler
    description: ${self:service} authorizer for adding metrics
    environment:
      AUTH_TOKEN: ${self:custom.config.authToken}
  AuthorizerGet:
    handler: src/infrastructure/adapters/web/Authorizer.handler
    description: ${self:service} authorizer for getting metrics
    environment:
      AUTH_TOKEN: ${self:custom.config.authToken}
  AddEvent:
    handler: src/infrastructure/adapters/web/AddEvent.handler
    description: Report new event (this will then be automatically also created as a change, deployment, or incident)
    events:
      - http:
          method: POST
          path: /event
          authorizer:
            name: AuthorizerAdd
            resultTtlInSeconds: ${self:custom.aws.apiGatewayCachingTtlValue}
            identitySource: method.request.querystring.authorization
            type: request
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
          - dynamodb:Query
        Resource: ${self:custom.aws.databaseArn}
    environment:
      REGION: ${self:provider.region}
      TABLE_NAME: ${self:custom.config.tableName}
      MAX_DATE_RANGE: ${self:custom.config.maxDateRange}
      SHORTCUT_TOKEN: ${self:custom.config.shortcutToken}
      SHORTCUT_INCIDENT_LABEL_ID: ${self:custom.config.shortcutIncidentLabelId}
  GetMetrics:
    handler: src/infrastructure/adapters/web/GetMetrics.handler
    description: Get DORA metrics
    events:
      - http:
          method: GET
          path: /metrics
          authorizer:
            name: AuthorizerGet
            resultTtlInSeconds: ${self:custom.aws.apiGatewayCachingTtlValue}
            identitySource: method.request.header.Authorization
            type: request
          cors:
            origin: '*'
            methods:
              - GET
            headers:
              - Content-Type
              - Authorization
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Credentials
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
          - dynamodb:Query
        Resource: ${self:custom.aws.databaseArn}
    environment:
      REGION: ${self:provider.region}
      TABLE_NAME: ${self:custom.config.tableName}
      MAX_DATE_RANGE: ${self:custom.config.maxDateRange}
  GetLastDeployment:
    handler: src/infrastructure/adapters/web/GetLastDeployment.handler
    description: Get the commit ID of the last production deployment
    events:
      - http:
          method: GET
          path: /lastdeployment
          authorizer:
            name: AuthorizerGet
            resultTtlInSeconds: ${self:custom.aws.apiGatewayCachingTtlValue}
            identitySource: method.request.header.Authorization
            type: request
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Query
        Resource: ${self:custom.aws.databaseArn}
    environment:
      REGION: ${self:provider.region}
      TABLE_NAME: ${self:custom.config.tableName}
      MAX_DATE_RANGE: ${self:custom.config.maxDateRange}

resources:
  Resources:
    # DynamoDB
    DorametrixTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        TableName: ${self:custom.config.tableName}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
    # API Gateway
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    AuthFailureExpiredGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureUnauthorizedGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'